name: HKRE Scheduled Scraper

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write Google service account credentials
        run: echo "$GOOGLE_CREDS_JSON" > service_account.json
        env:
          GOOGLE_CREDS_JSON: ${{ secrets.GOOGLE_CREDS_JSON }}

      - name: Run main script
        run: python main.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: service_account.json
