name: HKRE Scheduled Scraper

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDS_JSON: ${{ secrets.GOOGLE_CREDS_JSON }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Decode and write Google credentials
        run: |
          echo "$GOOGLE_CREDS_JSON" | base64 --decode > service_account.json

      - name: Run main script
        run: python main.py
